### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [Gameropt/prj-rev-bwfs-dasmoto#1]
For properties shared among elements, such as `font-family:Helvetica;` and `font-weight:bold;`, you could specify them all together like so:

```css
h1, .B, .C, .D, .E {
  font-family:Helvetica;
  font-weight:bold;
}
```

https://github.com/Gameropt/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%26%20Crafts/resources/css/style.css
